
archs = {
    "DBLP": [['AP', 'APT', 'APVP', 'APAPA', 'APTPA', 'APTPT', 'APTPV', 'APVPA', 'APVPV', 'APAPAP', 'APAPTP', 'APAPVP', 'APTPTP', 'APTPVP', 'APVPTP', 'APAPAPV', 'APAPTPA', 'APAPTPV', 'APAPVPA', 'APAPVPT', 'APAPVPV', 'APTPAPA', 'APTPAPT', 'APTPTPT', 'APTPVPV', 'APVPAPT', 'APVPTPA', 'APVPVPA', 'APVPVPT', 'APVPVPV'], []],
    "IMDB": [['MK', 'MKM', 'MAMK', 'MDMK', 'MKMA', 'MKMK', 'MAMAM', 'MAMKM', 'MDMAM', 'MKMAM', 'MKMDM', 'MKMKM', 'MAMAMD', 'MAMDMK', 'MAMKMD', 'MAMKMK', 'MDMKMA', 'MDMKMK', 'MKMAMD', 'MKMDMD', 'MKMKMD', 'MAMAMKM', 'MAMKMKM', 'MDMAMDM', 'MDMDMAM', 'MDMKMAM', 'MDMKMDM', 'MKMAMDM', 'MKMDMAM', 'MKMDMDM'], []],
    "ACM": [['PA', 'PP', 'PAPP', 'PPCP', 'PPPA', 'PPPP', 'PCPCP', 'PPCPC', 'PAPCPC', 'PCPPCP', 'PPAPCP', 'PPAPPC', 'PPPAPP', 'PAPAPAP', 'PAPPPPC', 'PCPAPPP', 'PCPPAPP', 'PCPPCPC', 'PCPPCPP', 'PPAPCPP', 'PPAPPPA', 'PPCPAPA', 'PPCPCPA', 'PPCPPPP', 'PPPAPPP', 'PPPCPCP', 'PPPCPPP', 'PPPPAPP', 'PPPPPAP', 'PPPPPPA'], []],
}
